apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: vulnerability-scan
spec:
  workspaces:
    - name: source
  steps:
    - name: trivy-scan
      image: aquasec/trivy:latest
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      resources:
        requests:
          memory: "500Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      script: |
        trivy fs \
          --exit-code 1 \
          --severity HIGH,CRITICAL \
          --no-progress \
          --cache-dir /tmp/trivy \
          --format json \
          --output trivy-results.json \
          $(workspaces.source.path)
        # Also scan the Rust dependencies
        trivy fs \
          --exit-code 1 \
          --severity HIGH,CRITICAL \
          --no-progress \
          --cache-dir /tmp/trivy \
          --format json \
          --output cargo-results.json \
          Cargo.lock 