apiVersion: v2
name: geospatial-api
description: A Helm chart for deploying the Geospatial API on OpenShift
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami 