apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geospatial-api.fullname" . }}-backup
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.storage.size }}
  storageClassName: {{ .Values.backup.storage.storageClass }} 