apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geospatial-api.fullname" . }}
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
data:
  RUST_LOG: {{ .Values.logLevel | default "info" }}
  {{- if .Values.extraConfig }}
  {{- toYaml .Values.extraConfig | nindent 2 }}
  {{- end }} 