apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "geospatial-api.fullname" . }}-init
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "geospatial-api.serviceAccountName" . }}
      containers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["psql"]
          args:
            - "-h"
            - "$(POSTGRES_HOST)"
            - "-U"
            - "postgres"
            - "-d"
            - "$(POSTGRES_DB)"
            - "-f"
            - "/init/init.sql"
          env:
            - name: POSTGRES_HOST
              value: {{ include "geospatial-api.postgresql.fullname" . }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "geospatial-api.postgresql.secretName" . }}
                  key: postgres-password
          volumeMounts:
            - name: init-sql
              mountPath: /init
      volumes:
        - name: init-sql
          configMap:
            name: {{ include "geospatial-api.fullname" . }}-postgres-init
      restartPolicy: OnFailure
  backoffLimit: 4 