apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "geospatial-api.fullname" . }}-limits
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      type: Container 