apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "geospatial-api.fullname" . }}
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "geospatial-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgresql
    - to:
        - podSelector:
            matchLabels:
              app: redis 