apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "geospatial-api.fullname" . }}-egress
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "geospatial-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system 