apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "geospatial-api.fullname" . }}
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "geospatial-api.selectorLabels" . | nindent 6 }} 