apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geospatial-api.fullname" . }}-postgres-init
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis; 