apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "geospatial-api.fullname" . }}-quota
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10" 