{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "geospatial-api.fullname" . }}
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 180s
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/rewrite-target: /
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "geospatial-api.fullname" . }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end }} 