apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geospatial-api.fullname" . }}
  labels:
    {{- include "geospatial-api.labels" . | nindent 4 }}
type: Opaque
data:
  master-api-key: {{ .Values.masterApiKey | b64enc }}
  {{- if .Values.extraSecrets }}
  {{- toYaml .Values.extraSecrets | nindent 2 }}
  {{- end }} 